M48
; DRILL file KiCad 10.0.6 date 2026-09-06T02:12:06
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-06T02:12:06+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X139.945Y-31.005
X139.945Y-36.005
T2
X109.67Y-26.5
X109.67Y-29.5
T3
X111.0Y-20.5
X111.0Y-48.0
X141.5Y-20.5
X141.5Y-48.0
M30
